//Pastas do Servidor//
#define   Pasta_SenhaAdm          "Administrativo/SenhaAdmin.cfg"
#define   Pasta_VeiculoLoja       "Administrativo/Loja.cfg"
#define   Pasta_Moedas            "Administrativo/Moedas Agendadas/%s.ini"
#define   Pasta_Casas             "Props/Casas/Casa_%d.ini"
#define   Pasta_Empresas          "Props/Empresas/Empresa_%d.ini"
#define   Pasta_SEmpresas         "Props/MiniEmpresas/MiniEmpresa_%d.ini"
#define   Pasta_FEmpresas         "Props/Fazendas/Fazenda_%d.ini"
#define   Pasta_Banidos           "Banimento/Banidos/%s.ini"
#define   Pasta_BanidosTemp       "Banimento/BanidosTemp/%s.ini"
#define   Pasta_IPBanidos         "Banimento/IPsBanidos/%s.ini"
#define   Pasta_IPBanidosTemp     "Banimento/IPsBanidosTemp/%s.ini"
#define   Pasta_CarrosVIP         "Carros VIPS/%d.ini"
#define   Pasta_CarrosFixo        "Carros Fixos/%d.ini"
#define   Pasta_ORGVIP            "Organizacoes/ORG VIPS/Org%d.ini"
#define   Pasta_CarrosFixados     "Carros Fixados/%d.ini"
#define   Pasta_CarrosTunados     "Carros Tunados/%d.ini"
#define   Pasta_Agendados         "Administrativo/Agendados/%s.ini"
#define   Pasta_Acessorio         "Players/Acessorios/%s.ini"
#define   Pasta_CAcessorio        "Players/Acessorios/Corpo/%s.ini"
#define   Pasta_UltimaPosicao     "Ultima Posicao/%s.ini"
#define   Pasta_Relatorios        "Administrativo/Relatorios/%d.ini"
#define   Pasta_Contas            "Players/Contas/%s.ini"
#define   Pasta_Deletadas         "Administrativo/ContasDeletadas/%s.ini"
#define   Pasta_Inventario        "Players/Inventario/%s.ini"
#define   Pasta_Logados           "Administrativo/Configs/Logados.ini"
#define   Pasta_Anuncio           "Anuncios/Moedas/%d.ini"
#define   Pasta_AnuncioItem       "Anuncios/Itens/%d.ini"
#define   Pasta_AnuncioVendido    "Anuncios/Vendido/%s.ini"
#define   Pasta_AnuncioItemVend   "Anuncios/Vendidoiten/%s.ini"
#define   Pasta_Concessionaria    "CarrosConce/%s.ini"
#define   Pasta_CofreOrg          "Organizacoes/Cofre Org/Org%d.cfg"
#define   Pasta_Candidatos        "Organizacoes/Candidatos/Org%d.cfg"
#define   Pasta_BUGS              "Administrativo/BUGS.ini"
#define   Pasta_Ranks             "rank/rank_%s.ini"
#define   Pasta_Emails            "Players/Emails/%s.ini"
